name: PrisonServerEssentials
main: NoUser123098\PrisonServerEssentials\main
version: 0.0.1
author: NoUser123098
api: [3.0.0]
load: POSTWORLD
commands:
  makerank:
    permission: pserveressentials.command.makerank
    description: "Creates a rank."
    usage: "/makerank <name> <format>"
  setrank:
    permission: pserveressentials.command.setrank
    description: "Sets a player's rank."
    usage: "/setrank <player>"
  setppermission:
    permission: pserveressentials.command.setppermission
    description: "Sets a permission for a player."
    usage: "/setppermission <player> <permission>"
  setgpermission:
    permission: pserveressentials.command.setgpermission
    description: "Sets a permission for a group."
    usage: "/setgpermission <group> <permission>"
  balance:
    permission: pserveressentials.command.balance
    description: "Checks your balance."
    usage: "/balance"
  givemoney:
    permission: pserveressentials.command.givemoney
    description: "Gives a player an amount of money."
    usage: "/givemoney <player> <amount>"
  setmoney:
    permission: pserveressentials.command.setmoney
    description: "Sets a player's amount of money."
    usage: "/setmoney <player> <amount>"
  makemine:
    permission: pserveressentials.command.makemine
    description: "Sets an area as a prison mine."
    usage: "/makemine <name>"
  setmine:
    permission: pserveressentials.command.setmine
    description: "Sets the blocks a mine will contain."
    usage: "/setmine <name> <id> <percent> etc..."
  resetmine:
    permission: pserveressentials.command.resetmine
    description: "Resets a mine."
    usage: "/resetmine <name>"
  resetallmines:
    permission: pserveressentials.command.resetallmines
    description: "Resets all mines."
    usage: "/resetallmines"
  protectedarea:
    permission: pserveressentials.command.protectarea
    description: "Protects an area."
    usage: "/protectedarea <pos1> <pos2> <name>"
  delprotected:
    permission: pserveressentials.command.delprotected
    description: "Deletes an area's protection."
    usage: "/delprotected <name>"
  makewarp:
    permission: pserveressentials.command.makewarp
    description: "Creates a warp."
    usage: "/makewarp <name>"
  delwarp:
    permission: pserveressentials.command.delwarp
    description: "Deletes a warp."
    usage: "/delwarp <name>"
  warp:
    permission: pserveressentials.command.warp
    description: "Warps you to a location."
    usage: "/warp <name>"
  nickname:
    permission: pserveressentials.command.nickname
    description: "Sets a custom nickname."
    usage: "/nickname <name>"
  signcmd:
    permission: pserveressentials.command.signcmd
    description: "Assigns a command to a sign."
    usage: "/signcmd <command>"
  disguise:
    permission: pserveressentials.command.disguise
    description: "Disguises a player as a mob."
    usage: "/disguise <player> <entity>"
