name: PrisonServerEssentials
main: NoUser123098\PrisonServerEssentials\main
version: 0.0.1
author: NoUser123098
api: [3.2.3]
load: POSTWORLD
commands:
  makerank:
    permission: pserveressentials.command.makerank
    description: "Creates a rank."
    usage: "/makerank <name> <format>"
  setrank:
    permission: pserveressentials.command.setrank
    description: "Sets a player's rank."
    usage: "/setrank <player>"
  setppermission:
    permission: pserveressentials.command.setppermission
    description: "Sets a permission for a player."
    usage: "/setppermission <player> <permission>"
  setgpermission:
    permission: pserveressentials.command.setgpermission
    description: "Sets a permission for a group."
    usage: "/setgpermission <group> <permission>"
  balance:
    permission: pserveressentials.command.balance
    description: "Checks your balance."
    usage: "/balance"
  givemoney:
    permission: pserveressentials.command.givemoney
    description: "Gives a player an amount of money."
    usage: "/givemoney <player> <amount>"
  setmoney:
    permission: pserveressentials.command.setmoney
    description: "Sets a player's amount of money."
    usage: "/setmoney <player> <amount>"
  makemine:
    permission: pserveressentials.command.makemine
    description: "Sets an area as a prison mine."
    usage: "/makemine <name>"
  setmine:
    permission: pserveressentials.command.setmine
    description: "Sets the blocks a mine will contain."
    usage: "/setmine <name> <id> <percent> etc..."
  resetmine:
    permission: pserveressentials.command.resetmine
    description: "Resets a mine."
    usage: "/resetmine <name>"
  resetallmines:
    permission: pserveressentials.command.resetallmines
    description: "Resets all mines."
    usage: "/resetallmines"
  makeprotected:
    permission: pserveressentials.command.makeprotected
    description: "Protects an area."
    usage: "/makeprotected <pos1> <pos2> <name>"
  delprotected:
    permission: pserveressentials.command.delprotected
    description: "Deletes an area's protection."
    usage: "/delprotected <name>"
  makewarp:
    permission: pserveressentials.command.makewarp
    description: "Creates a warp."
    usage: "/makewarp <name>"
  delwarp:
    permission: pserveressentials.command.delwarp
    description: "Deletes a warp."
    usage: "/delwarp <name>"
  warp:
    permission: pserveressentials.command.warp
    description: "Warps you to a location."
    usage: "/warp <name>"
  nickname:
    permission: pserveressentials.command.nickname
    description: "Sets a custom nickname."
    usage: "/nickname <name>"
  signcmd:
    permission: pserveressentials.command.signcmd
    description: "Assigns a command to a sign."
    usage: "/signcmd <command>"
  disguise:
    permission: pserveressentials.command.disguise
    description: "Disguises a player as a mob."
    usage: "/disguise <player> <entity>"
  display:
    permission: pserveressentials.command.display
    description: "Displays an item on a slab or inside glass."
    usage: "/display"
  checkinv:
    permission: pserveressentials.command.checkinv
    description: "Look into another player's inventory."
    usage: "/checkinv <player>"
  claimplot:
    permission: pserveressentials.command.claimplot
    description: "Claims a plot."
    usage: "/claimplot"
  unclaimplot:
    permission: pserveressentials.command.unclaimplot
    description: "Unclaims a plot."
    usage: "/unclaimplot"
  createplot:
    permission: pserveressentials.command.createplot
    description: "Creates a plot world."
    usage: "/createplot <name>"
  autocmd:
    permission: pserveressentials.command.autocmd
    description: "Runs a command automatically."
    usage: "/autocmd <command> <seconds>"
  broadcast:
    permission: pserveressentials.command.broadcast
    description: "Broadcasts a message."
    usage: "/broadcast <message>"
  register:
    permission: pserveressentials.command.register
    description: "Registers a player."
    usage: "/register <password>"
  login:
    permission: pserveressentials.command.login
    description: "Logs a player in."
    usage: "/login <password>"
  makestatue:
    permission: pserveressentials.command.makestatue
    description: "Creates a statue from an entity."
    usage: "/makestatue <nametag> [mob]"
  vanish:
    permission: pserveressentials.command.vanish
    description: "Makes a player invisible."
    usage: "/vanish [player]"
  enterlottery:
    permission: pserveressentials.command.enterlottery
    description: "Enters the lottery with the selected numbers."
    usage: "/enterlottery <num1> <num2> <num3> <num4> <num5>"
  lockchest:
    permission: pserveressentials.command.lockchest
    description: "Allows only one player to access the clicked chest."
    usage: "/lockchest"
  unlockchest:
    permission: pserveressentials.command.unlockchest
    description: "Unlocks the clicked locked chest."
    usage: "/unlockchest"
  joinmessage:
    permission: pserveressentials.command.joinmessage
    description: "Sets the player join message."
    usage: "/joinmessage <message>"
  makekit:
    permission: pserveressentials.command.makekit
    description: "Creates a kit."
    usage: "/makekit <name> <id1> <id2> etc..."
  kit:
    permission: pserveressentials.command.kit
    description: "Gives a kit to a player."
    usage: "/kit <name> [player]"
  rankup:
    permission: pserveressentials.command.rankup
    description: "Ranks up to the next mine."
    usage: "/rankup [rank]"
  maketext:
    permission: pserveressentials.command.maketext
    description: "Makes floating text at current position or specified coordinates."
    usage: "/maketext <name> <text> [pos1] [pos2]"
  deltext:
    permission: pserveressentials.command.deltext
    description: "Deletes floating text."
    usage: "/deltext <name>"
permissions:
  pserveressentials.*:
    default: op
    description: "Gives all permissions."
    children:
      pserveressentials.command.makerank:
        description: "The makerank command permission."
        default: op
      pserveressentials.command.setrank:
        description: "The setrank command permission."
        default: op
      pserveressentials.command.setppermission:
        description: "The setppermission command permission."
        default: op
      pserveressentials.command.setgpermission:
        description: "The setgpermission command permission."
        default: op
      pserveressentials.command.balance:
        description: "The balance permission."
        default: true
      pserveressentials.command.givemoney:
        description: "The givemoney command permission."
        default: op
      pserveressentials.command.setmoney:
        description: "The setmoney command permission."
        default: op
      pserveressentials.command.makemine:
        description: "The makemine command permission."
        default: op
      pserveressentials.command.setmine:
        description: "The setmine command permission."
        default: op
      pserveressentials.command.resetmine:
        description: "The resetmine command permission."
        default: op
      pserveressentials.command.resetallmines:
        description: "The resetallmines command permission."
        default: op
      pserveressentials.command.makeprotected:
        description: "The makeprotected command permission."
        default: op
      pserveressentials.command.delprotected:
        description: "The delprotected command permission."
        default: op
      pserveressentials.command.makewarp:
        description: "The makewarp command permission."
        default: op
      pserveressentials.command.delwarp:
        description: "The delwarp command permission."
        default: op
      pserveressentials.command.warp:
        description: "The warp command permission."
        default: true
      pserveressentials.command.nickname:
        description: "The nickname command permission."
        default: op
      pserveressentials.command.signcmd:
        description: "The signcmd command permission."
        default: op
      pserveressentials.command.disguise:
        description: "The disguise command permission."
        default: op
      pserveressentials.command.display:
        description: "The display command permission."
        default: op
      pserveressentials.command.checkinv:
        description: "The checkinv command permission."
        default: op
      pserveressentials.command.claimplot:
        description: "The claimplot command permission."
        default: true
      pserveressentials.command.unclaimplot:
        description: "The unclaimplot command permission."
        default: true
      pserveressentials.command.createplot:
        description: "The createplot command permission."
        default: op
      pserveressentials.command.autocmd:
        description: "The autocmd command permission."
        default: op
      pserveressentials.command.broadcast:
        description: "The broadcast command permission."
        default: op
      pserveressentials.command.register:
        description: "The register command permission."
        default: true
      pserveressentials.command.login:
        description: "The login command permission."
        default: true
      pserveressentials.command.makestatue:
        description: "The makestatue command permission."
        default: op
      pserveressentials.command.vanish:
        description: "The vanish command permission."
        default: op
      pserveressentials.command.enterlottery:
        description: "The enterlottery command permission."
        default: true
      pserveressentials.command.lockchest:
        description: "The lockchest command permission."
        default: true
      pserveressentials.command.unlockchest:
        description: "The unlockchest command permission."
        default: true
      pserveressentials.command.joinmessage:
        description: "The joinmessage command permission."
        default: op
      pserveressentials.command.makekit:
        description: "The makekit command permission."
        default: op
      pserveressentials.command.kit:
        description: "The kit command permission."
        default: true
      pserveressentials.command.rankup:
        description: "The rankup command permission."
        default: true
      pserveressentials.command.maketext:
        description: "The maketext command permission."
        default: op
      pserveressentials.command.deltext:
        description: "The deltext command permission."
        default: op
